esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}

# disable mdns
mdns:
  disabled: true

# enable ota update
# todo: refactor to download updates from a server
ota:
  - platform: esphome
    password: !secret flash_password

# only log relevant stuff
logger:
  level: WARN

wifi:
  domain: ".gob.zone"
  fast_connect: false
  reboot_timeout: "60s"
  networks:
    - ssid: "gob"
      password: !secret gob_password
