esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}

# disable mdns
mdns:
  disabled: true

# enable hass api
api:
  encryption:
      key: !secret encryption_key

# enable ota update
ota:
  password: !secret flash_password

wifi:
  domain: ".gob.zone"
  fast_connect: false
  passive_scan: false
  networks:
    - ssid: "banzai_2.4"
      password: !secret kendo_password
    - ssid: "kendo_2.4"
      password: !secret kendo_password
    - ssid: "gob"
      password: !secret gob_password

  ap:
    ssid: "esphome"
    password: !secret ap_password
