esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}

# disable mdns
mdns:
  disabled: true

# enable ota update
# todo: refactor to download updates from a server
ota:
  - platform: esphome
    password: !secret flash_password

# only log relevant stuff
logger:
  level: WARN

mqtt:
  broker: chump.gob.zone
  # clean_session seems to get activated sometimes (2025-03-16)
  # i don't know the reason yet. lets disable to prevent problems
  clean_session: false
  # defaults to 15. maybe it helps
  keepalive: "15s"
  discovery_unique_id_generator: mac
  discovery_object_id_generator: device_name
  log_topic:
    topic: esphome/logs/${name}
    level: WARN

wifi:
  domain: ".gob.zone"
  fast_connect: false
  reboot_timeout: "60s"
  networks:
    - ssid: "gob"
      password: !secret gob_password
