esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}

# disable mdns
mdns:
  disabled: true

# enable hass api
api:
  encryption:
      key: !secret encryption_key

# enable ota update
ota:
  - platform: esphome
    password: !secret flash_password

logger:

wifi:
  domain: ".gob.zone"
  fast_connect: false
  reboot_timeout: "60s"
  networks:
    - ssid: "gob"
      password: !secret gob_password
