esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}

# disable mdns
mdns:
  disabled: true

mqtt:
  broker: chump.gob.zone
  clean_session: true
  discovery_unique_id_generator: mac

# enable ota update
ota:
  - platform: esphome
    password: !secret flash_password

api: # only used for logs
  encryption:
      key: !secret encryption_key
  reboot_timeout: 0

logger:
  level: WARN
# TODO: Add setting for configurable log level

wifi:
  domain: ".gob.zone"
  fast_connect: false
  reboot_timeout: "60s"
  networks:
    - ssid: "gob"
      password: !secret gob_password
