esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build

# enable hass api
api:
  encryption:
      key: !secret encryption_key

# enable ota update
ota:
  password: !secret flash_password

wifi:
  domain: ".gob.zone"
  fast_connect: false
  networks:
    - ssid: "gob"
      password: !secret gob_password
  ap:
    ssid: "esphome"
    password: !secret ap_password

debug:
    update_interval: 5s
