substitutions:
  name: "shelly_1882"
  description: "Shelly that sends a http request to shelly_1741 on switch"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  build_path: ../build/${name}
  esp8266_restore_from_flash: true

logger:
    esp8266_store_log_strings_in_flash: false

wifi:
  domain: ".gob.zone"
  fast_connect: true
  networks:
    - ssid: "kendo_2.4"
      password: !secrets kendo_password
  ap:
    ssid: ${name}
    password: !secreds ssid_password
captive_portal:

ota:
web_server:
  port: 80

http_request:
  useragent: esphome/${name}
  timeout: 10s
  esp8266_disable_ssl_support: true

binary_sensor:
  - platform: gpio
    id: ${name}_switch
    name: ${name}_switch
    pin:
      number: GPIO5
    on_state:
        - http_request.post:
            url: http://shelly_1741/light/shelly_1741_light/toggle
