substitutions:
  name: "tcl"

<<: !include ../global/global.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: false

esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}
  on_boot:
    priority: 800
    then:
      - remote_transmitter.transmit_nec:
          address: 0xE710
          command: 0xF50A
          command_repeats: 1

remote_transmitter:
  pin:
    number: GPIO02
    inverted: true
    mode:
      output: true
  carrier_duty_percent: 100%

button:
#  - platform: template
#    name: ${name}_source_bluetooth
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xF10E
#          command_repeats: 1
#  - platform: template
#    name: ${name}_source_optical
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xF20D
#          command_repeats: 1
#  - platform: template
#    name: ${name}_source_1
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xF50A
#          command_repeats: 1
#  - platform: template
#    name: ${name}_source_2
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xEA15
#          command_repeats: 1
#  - platform: template
#    name: ${name}_sourc_coax
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xE916
#          command_repeats: 1
  - platform: template
    name: ${name}_on_off
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xE710
          command: 0xFE01
          command_repeats: 1
  - platform: template
    name: ${name}_mute
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xE710
          command: 0xFF00
          command_repeats: 1
  - platform: template
    name: ${name}_volume_up
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xE710
          command: 0xF609
          command_repeats: 1
  - platform: template
    name: ${name}_volume_down
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xE710
          command: 0xF30C
          command_repeats: 1
#  - platform: template
#    name: ${name}_bt_play_pause
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xEB14
#          command_repeats: 1
#  - platform: template
#    name: ${name}_bt_previous
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xF906
#          command_repeats: 1
#  - platform: template
#    name: ${name}_bt_next
#    on_press:
#      - remote_transmitter.transmit_nec:
#          address: 0xE710
#          command: 0xF708
#          command_repeats: 1
