substitutions:
  name: shelly_25

<<: !include ../defaults/global.yaml
<<: !include ../defaults/esp8266.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true
#  early_pin_init: false

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - <<: !include ../defaults/wifi_sensor.yaml
  - platform: uptime
    id: timer
    name: ${name}_uptime

  - platform: ade7953
    irq_pin: GPIO16
    voltage:
      name: ${name}_voltage
      filters:
        - delta: 1
    current_a:
      id: current_a
      name: ${name}_current_a
      filters:
        - delta: 0.1
    current_b:
      id: current_b
      name: ${name}_current_b
      filters:
        - delta: 0.1
    active_power_a:
      name: ${name}_power_a
      filters:
        - delta: 1
    active_power_b:
      name: ${name}_power_b
      filters:
        - multiply: -1
        - delta: 1
    update_interval: 0.5s

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${name}_temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      above: 90
      then:
        - switch.turn_on: _shutdown

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

text_sensor:
  - <<: !include ../defaults/wifi_text_sensor.yaml
  - platform: template
    name: ${name}_devicename
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Shelly 2.5"};
  - platform: template
    name: ${name}_devicetype
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Cover"};

switch:
  - platform: gpio
    id: powered_a
    pin: GPIO15
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock [powered_a, powered_b]
    interlock_wait_time: 200ms

  - platform: gpio
    id: powered_b
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock
    interlock_wait_time: 200ms

  - platform: shutdown
    id: _shutdown

binary_sensor:
  - platform: gpio
    id: ADE7953
    pin: GPIO16

  - platform: gpio
    pin:
      number: GPIO13
    name: ${name}_switch_a
    on_press:
      then:
        - switch.turn_on: powered_a
    on_release:
      then:
        - switch.turn_off: powered_a
  - platform: gpio
    pin:
      number: GPIO5
    name: ${name}_switch_b
    on_press:
      then:
        - switch.turn_on: powered_b
    on_release:
      then:
        - switch.turn_off: powered_b

cover:
  - platform: current_based
    id: cvr
    name: ${name}_cover
    open_sensor: current_b
    open_moving_current_threshold: 0.2
    open_obstacle_current_threshold: 0.8
    open_duration: 36s
    open_action:
      - switch.turn_on: powered_b

    close_sensor: current_a
    close_moving_current_threshold: 0.2
    close_obstacle_current_threshold: 0.8
    close_duration: 32s
    close_action:
      - switch.turn_on: powered_a

    stop_action:
      - switch.turn_off: powered_a
      - switch.turn_off: powered_b
