substitutions:
  name: shelly_1v3
!!merge <<: !include ../global/global.yaml
esp8266:
  board: esp01_1m
  restore_from_flash: true
switch:
  - platform: gpio
    id: powered
    name: ${name}_powered
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    id: enable_button
    name: ${name}_enable_button
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    id: enable_switch
    name: ${name}_enable_switch
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    id: standalone_mode
    name: ${name}_standalone_mode
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO05
    id: sw
    name: ${name}_switch
    on_press:
      if:
        condition:
          and:
            - switch.is_on: enable_button
            - or:
                - switch.is_on: standalone_mode
                - not:
                    mqtt.connected:
        then:
          - switch.toggle: powered
    on_state:
      if:
        condition:
          and:
            - switch.is_on: enable_switch
            - or:
                - switch.is_on: standalone_mode
                - not:
                    mqtt.connected:
        then:
          - switch.toggle: powered
