substitutions:
  name: shelly_2plus_switch

<<: !include ../global/global.yaml

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

i2c:
  sda: GPIO26
  scl: GPIO25

sensor:
  - <<: !include ../global/wifi_sensor.yaml
  - platform: uptime
    id: timer
    name: ${name}_uptime

  - platform: ade7953_i2c
    irq_pin: GPIO27
    update_interval: 0.5s
    voltage:
      name: ${name}_voltage
      filters:
        - or:
          - delta: 1
          - heartbeat: 60s
    current_a:
      name: ${name}_current_o1
      filters:
        - delta: 0.1
        - heartbeat: 60s

    current_b:
      name: ${name}_current_o2
      filters:
        - or:
          - delta: 0.1
          - heartbeat: 60s

    active_power_a:
      name: ${name}_power_o1
      filters:
        - multiply: -1
        - or:
          - delta: 1
          - heartbeat: 60s

    active_power_b:
      name: ${name}_power_o2
      filters:
        - multiply: -1
        - or:
          - delta: 1
          - heartbeat: 60s

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${name}_temperature
    unit_of_measurement: "°C"
    entity_category: diagnostic
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 4.7kOhm
      reference_temperature: 298.15K
    on_value_range:
      above: 90
      then:
        - switch.turn_on: _shutdown

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 5.6kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO35
    attenuation: 11db

# led
output:
  - platform: gpio
    id: led
    pin:
      number: GPIO0
      inverted: true

switch:
  - platform: gpio
    id: powered_o1
    name: ${name}_powered_o1
    pin: GPIO13
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: powered_o2
    name: ${name}_powered_o2
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: shutdown
    id: _shutdown

  - platform: template
    id: swap_switch
    name: ${name}_swap_switch
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    id: switch_s1
    pin:
      number: GPIO18
    on_state:
      if:
        condition:
          - switch.is_on: swap_switch
        then:
          - switch.toggle: powered_o2
        else:
          - switch.toggle: powered_o1

  - platform: gpio
    id: switch_s2
    pin:
      number: GPIO5
    on_state:
      if:
        condition:
          - switch.is_on: swap_switch
        then:
          - switch.toggle: powered_o1
        else:
          - switch.toggle: powered_o2
