substitutions:
  name: shelly_1v3

<<: !include ../global/global.yaml
<<: !include ../global/esp8266.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true
#  early_pin_init: false


switch:
  - platform: gpio
    id: powered
    name: ${name}_powered
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    id: enable_button
    name: ${name}_enable_button
    entity_category: config
    optimistic: true
    restore_state: true
  - platform: template
    id: enable_switch
    name: ${name}_enable_switch
    entity_category: config
    optimistic: true
    restore_state: true
  - platform: template
    id: standalone_mode
    name: ${name}_standalone_mode
    entity_category: config
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO05
    id: sw
    name: ${name}_switch
    on_press:
      if:
        condition:
          and:
            - switch.is_on: enable_button
            - or:
              - switch.is_on: standalone_mode
              - not:
                  api.connected:
        then:
          - switch.toggle: powered
    on_state:
      if:
        condition:
          and:
            - switch.is_on: enable_switch
            - or:
              - switch.is_on: standalone_mode
              - not:
                  api.connected:
        then:
          - switch.toggle: powered

sensor:
  - <<: !include ../global/wifi_sensor.yaml
  - <<: !include ../global/debug_sensor.yaml
  - platform: uptime
    name: ${name}_uptime

text_sensor:
  - <<: !include ../global/wifi_text_sensor.yaml
  - platform: debug
    device:
      name: ${name}_deviceinfo
  - platform: template
    name: ${name}_devicename
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Shelly 1v3"};
  - platform: template
    name: ${name}_devicetype
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Switch"};


