substitutions:
  name: vansware_mss

<<: !include ../defaults/global.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: false
#  early_pin_init: false

output:
  - platform: esp8266_pwm
    pin: GPIO00
    id: output_led_r
  - platform: esp8266_pwm
    pin: GPIO02
    id: output_led_b
  - platform: esp8266_pwm
    pin: GPIO04
    id: output_led_g

light:
  - platform: rgb
    id: led
    name: ${name}_color
    red: output_led_r
    green: output_led_g
    blue: output_led_b
    entity_category: config

switch:
  - platform: gpio
    id: powered
    name: ${name}_powered
    pin: GPIO15
    on_turn_on:
      if:
        condition:
          switch.is_on: enable_led
        then:
          - light.turn_on: led
    on_turn_off:
      if:
        condition:
          switch.is_on: enable_led
        then:
          - light.turn_off: led
  - platform: template
    id: enable_button
    name: ${name}_enable_button
    entity_category: config
    optimistic: true
  - platform: template
    id: enable_led
    name: ${name}_enable_led_on_power
    entity_category: config
    optimistic: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    id: button
    name: ${name}_button
    on_press:
      if:
        condition:
          switch.is_on: enable_button
        then:
          - switch.toggle: powered

sensor:
  - <<: !include ../defaults/wifi_sensor.yaml
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current:
      name: ${name}_current
      unit_of_measurement: A
    voltage:
      name: ${name}_voltage
      unit_of_measurement: V
    power:
      name: ${name}_power
      unit_of_measurement: W
    change_mode_every: 1
    voltage_divider: 900
    update_interval: 10s
  - platform: uptime
    name: ${name}_uptime

text_sensor:
  - <<: !include ../defaults/wifi_text_sensor.yaml
  - platform: template
    name: ${name}_devicename
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Vansware Mini Smart Socket"};
  - platform: template
    name: ${name}_devicetype
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Smartplug"};
