esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build

# enable logging
logger:
    esp8266_store_log_strings_in_flash: false
    baud_rate: 0 # disable logging via uart
    #level: VERY_VERBOSE

# enable hass api
api:
  password: !secret api_password

# enable ota update
ota:
  password: !secret flash_password

wifi:
  domain: ".gob.zone"
  fast_connect: false
  networks:
    - ssid: "gob"
      password: !secret gob_password
  ap:
    ssid: "esphome"
    password: !secret ap_password 
