substitutions:
  name: humidifier
!!merge <<: !include ../global/global.yaml
esp8266:
  board: d1_mini
  restore_from_flash: false
remote_transmitter:
  pin:
    number: GPIO2
    inverted: true
    mode:
      output: true
  carrier_duty_percent: 100%
sensor:
  - platform: adc
    pin: GPIO17
    name: ${name}_running
    update_interval: 1s
button:
  - platform: template
    name: ${name}_on_off
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xFF00
          command_repeats: 1
  - platform: template
    name: ${name}_intermittent
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xFE01
          command_repeats: 1
  - platform: template
    name: ${name}_continous
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xFD02
          command_repeats: 1
  - platform: template
    name: ${name}_timing
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xF708
          command_repeats: 1
  - platform: template
    name: ${name}_big_small
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xF609
          command_repeats: 1
  - platform: template
    name: ${name}_light
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xF50A
          command_repeats: 1
