substitutions:
  name: esp32_cam

<<: !include ../global/global.yaml

esp32:
  board: node32s
  #board: esp32cam
  framework:
    type: esp-idf # doesn't support cam

psram:
  speed: 120MHz

#logger:
#  level: DEBUG

api:

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "${name}_light"

esp32_camera:
  id: "camera"
  name: "${name}_camera"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1920x1080
  jpeg_quality: 30

#debug:
#  update_interval: 5s
#
#sensor:
#  - platform: debug
#    free:
#      name: "${name} Heap Free"
#    block:
#      name: "${name} Heap Max Block"
#    loop_time:
#      name: "${name} Loop Time"
#    psram:
#      name: "${name} Free PSRAM"
