substitutions:
  name: esp32_cam

<<: !include ../global/global.yaml
<<: !include ../global/esp32.yaml

esp32:
  board: node32s
  #board: esp32cam
  #framework:
  #  type: esp-idf



output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "${name}_light"

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

esp32_camera:
  name: "${name}_camera"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  #max_framerate: 15 fps
  #idle_framerate: 1 fps
  #resolution: 640x480
  #jpeg_quality: 10

switch:
  - platform: restart
    name: "${name}_restart"
