substitutions:
  name: esp32_cam

<<: !include ../global/global.yaml
<<: !include ../global/esp32.yaml

esp32:
  board: node32s


sensor:
  - <<: !include ../global/wifi_sensor.yaml
  - <<: !include ../global/debug_sensor.yaml
  - platform: uptime
    name: ${name}_uptime


text_sensor:
  - <<: !include ../global/wifi_text_sensor.yaml
  - platform: debug
    device:
      name: ${name}_deviceinfo
  - platform: template
    name: ${name}_devicename
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"ESP32 CAM"};
  - platform: template
    name: ${name}_devicetype
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Camera"};

esp32_camera:
  name: "${camera_name}"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  max_framerate: 5 fps    # default: 10 fps, max 60
  idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  resolution: 800x600     # default: 640x480 (VGA) - higher res requires more memory
  jpeg_quality: 10        # 10 (best) to 63 (worst)
