substitutions:
  name: magichome
!!merge <<: !include ../global/global.yaml
esp8266:
  board: esp01_1m
  restore_from_flash: true
#  early_pin_init: false

output:
  - platform: esp8266_pwm
    pin: GPIO05
    id: gpio_5
  - platform: esp8266_pwm
    pin: GPIO12
    id: gpio_12
  - platform: esp8266_pwm
    pin: GPIO13
    id: gpio_13
#  - platform: esp8266_pwm
#    pin: GPIO15
#    id: gpio_15

light:
  - platform: rgb
    id: ${name}_light
    name: ${name}_light
    red: gpio_5
    green: gpio_13
    blue: gpio_12
#    white: gpio_15
#    gamma_correct: 1.8

sensor:
  - platform: uptime
    name: ${name}_uptime
