substitutions:
  name: magichome
!!merge <<: !include ../global/global.yaml
esp8266:
  board: esp8285
  restore_from_flash: true
#  early_pin_init: false

output:
  - platform: esp8266_pwm
    pin: GPIO05
    id: gpio_5
  - platform: esp8266_pwm
    pin: GPIO12
    id: gpio_12
  - platform: esp8266_pwm
    pin: GPIO13
    id: gpio_13
  - platform: esp8266_pwm
    pin: GPIO15
    id: gpio_15
light:
  - platform: rgbw
    id: ${name}_light
    name: ${name}_light
    red: gpio_12
    blue: gpio_13
    green: gpio_5
    white: gpio_15
    color_interlock: false
#    gamma_correct: 1.8

sensor:
  - platform: uptime
    name: ${name}_uptime
