substitutions:
  name: magichome

<<: !include ../defaults/global.yaml
<<: !include ../defaults/esp8266.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true
#  early_pin_init: false

output:
  - platform: esp8266_pwm
    pin: GPIO05
    id: gpio_5
  - platform: esp8266_pwm
    pin: GPIO12
    id: gpio_12
  - platform: esp8266_pwm
    pin: GPIO13
    id: gpio_13
#  - platform: esp8266_pwm
#    pin: GPIO15
#    id: gpio_15

light:
  - platform: rgb
    id: ${name}_light
    name: ${name}_light
    red: gpio_5
    green: gpio_13
    blue: gpio_12
#    white: gpio_15
#    gamma_correct: 1.8

sensor:
  - <<: !include ../defaults/wifi_sensor.yaml
  - <<: !include ../defaults/debug_sensor.yaml
  - platform: uptime
    name: ${name}_uptime

text_sensor:
  - <<: !include ../defaults/wifi_text_sensor.yaml
  - platform: debug
    device:
      name: ${name}_deviceinfo
  - platform: template
    name: ${name}_devicename
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Magic Home LED Controller"};
  - platform: template
    name: ${name}_devicetype
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return {"Light"};
