substitutions:
  name: nodemcu
!!merge <<: !include ../global/global.yaml
esp8266:
  board: nodemcuv2
  restore_from_flash: false
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${name}_power
