substitutions:
  name: esplouder

<<: !include ../global/global.yaml

esp32:
  board: wemos_d1_mini32

esphome:
  name: ${name}
  name_add_mac_suffix: true
  build_path: ../build/${name}
  includes:
    - tas5805m.hpp
    - ding-dong.h
    - span/include
  platformio_options:
    build_flags:
      - -Isrc/include
      - -DTCB_SPAN_NAMESPACE_NAME=std

external_components:
  - source:
      type: local
      path: components
    components: [speaker]

psram:
  mode: octal
  speed: 80MHz

i2c:
  sda: GPIO21
  scl: GPIO27

i2s_audio:
  i2s_lrclk_pin: GPIO25 # WS/FS
  i2s_bclk_pin: GPIO26  # SCK

switch:
- platform: custom
  lambda: |-
    auto tas5805m = new TAS5805();
    App.register_component(tas5805m);
    return {tas5805m};
  switches:
    name: "Enable Amp"

speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO022
    mode: mono


button:
  - platform: template
    name: "Play embedded Media"
    on_press:
      - speaker.play: !lambda return lowPCM;



